### ISSUE TITLE
Error on local deploy

### ISSUE THREAD

**Issue by KingLouisXVII** [zeppelinos/crafty#78]
I am getting this message after running `npm run deploy local`. Dependencies are installed and tests passed. Running Ganache in a separate Terminal.

`> crafty@1.0.0 deploy /Users/danieljakobian/Sites/Privat/crafty
> bash bin/deploy.sh "local"

Using network 'local'.

fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/danieljakobian/Sites/Privat/crafty/build/contracts'
    at Object.fs.readdirSync (fs.js:904:18)
    at FS.getContractName (/Users/danieljakobian/Sites/Privat/crafty/node_modules/truffle/build/cli.bundled.js:115800:22)
    at FS.require (/Users/danieljakobian/Sites/Privat/crafty/node_modules/truffle/build/cli.bundled.js:115779:28)
    at Resolver.require (/Users/danieljakobian/Sites/Privat/crafty/node_modules/truffle/build/cli.bundled.js:61758:25)
    at /Users/danieljakobian/Sites/Privat/crafty/deploy/deploy.js:4:26
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at ContextifyScript.Script.runInNewContext (vm.js:65:15)
    at /Users/danieljakobian/Sites/Privat/crafty/node_modules/truffle/build/cli.bundled.js:115720:14
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! crafty@1.0.0 deploy: `bash bin/deploy.sh "local"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the crafty@1.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by nventuro** [comment]
Deployment failed because the contract artifacts were not compiled: you need to run `npm run build` before attempting to deploy. I [added this to the readme](https://github.com/zeppelinos/crafty/pull/79), thanks!
