### ISSUE TITLE
Error: Web3ProviderEngine does not support synchronous requests

### ISSUE THREAD

**Issue by haraldini** [zeppelinos/crafty#80]
Fresh git clone, deploys locally without a problem.

`npm run deploy ropsten_infura` will fail with error above

**Comment by nventuro** [comment]
Hmm, maybe something changed in Infura? I recall deploying on ropsten with no issues. Could you detail which method it is that is unsupported? Thanks!

**Comment by haraldini** [comment]
This is error message

`$ npm run deploy ropsten_infura`

```
> crafty@1.0.0 deploy /Users/username/projects/ethereum/crafty
> bash bin/deploy.sh "ropsten_infura"

Using network 'ropsten_infura'.


/Users/username/projects/ethereum/crafty/node_modules/truffle/build/webpack:/~/truffle-error/index.js:10
  this.stack = (new Error(message)).stack;
^
/Users/username/projects/ethereum/crafty/node_modules/truffle/build/cli.bundled.js:209306
        throw error;
        ^

Error: Web3ProviderEngine does not support synchronous requests.
    at ProviderError.ExtendableError (/Users/username/projects/ethereum/crafty/node_modules/truffle/build/webpack:/~/truffle-error/index.js:10:1)
    at new ProviderError (/Users/username/projects/ethereum/crafty/node_modules/truffle/build/webpack:/~/truffle-provider/error.js:17:1)
    at /Users/username/projects/ethereum/crafty/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:71:1
    at HDWalletProvider.send (/Users/username/projects/ethereum/crafty/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:109:1)
    at RequestManager.send (/Users/username/projects/ethereum/crafty/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:58:1)
    at Eth.get [as accounts] (/Users/username/projects/ethereum/crafty/node_modules/truffle/build/webpack:/~/web3/lib/web3/property.js:107:1)
    at /Users/username/projects/ethereum/crafty/deploy/deploy.js:17:31
    at Script.runInContext (vm.js:102:20)
    at Script.runInNewContext (vm.js:108:17)
    at /Users/username/projects/ethereum/crafty/node_modules/truffle/build/webpack:/~/truffle-require/require.js:97:1
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! crafty@1.0.0 deploy: `bash bin/deploy.sh "ropsten_infura"`
npm ERR! Exit status 1
npm ERR!
```

**Comment by nventuro** [comment]
That is positively bizarre, it looks like the offending line is 

```
const adminAddress = web3.eth.accounts[1];
```

**Comment by medied** [comment]
@nventuro any updates on this issue?  Seeing the same error message when trying to deploy to rinkeby with Infura
